9863 Replace homepage slider with a more modern, accessible plugin
archesproject/arches pull request #10068
Opened 2023-09-25 14:31 UTC by phudson-he

### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change
Replacement of the old Revolution Slider with [accessible-slick](https://accessible360.github.io/accessible-slick/). Also made changes in order to make fully responsive and cater for smaller screens in either portrait or landscape orientation.

### Issues Solved
#9863 

### Checklist

-   [x] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: Historic England
*   Found by: @phudson-he
*   Tested by: @phudson-he
*   Designed by: @phudson-he

2023-09-28 18:42 UTC, johnatawnclementawn requested changes
While I agree that it would be great to rip out revolution slider and all of the cruft that comes with, after consulting with Alexei and Cyrus, we think it'd be best to keep those files so as to not break the index page for any projects that have customized it already.

2023-10-18 15:07 UTC, phudson-he commented
Just to note, the default index.htm uses the new code for the accessible slick slider. if a user wants to use the old, non-accessible revolution slider, I've included a new file called index-revolution.htm with all the appropriate legacy code to run.

2023-10-31 15:22 UTC, johnatawnclementawn commented on arches/app/templates/index.htm
> +                            <p>{% trans "zzA web and mobile platform for" %}</p>
'zz' typo

2023-10-31 15:23 UTC, johnatawnclementawn commented on arches/install/arches-templates/project_name/templates/index.htm
> +                            <p>{% trans "zzA web and mobile platform for" %}</p>
'zz' typo

2023-10-31 15:50 UTC, johnatawnclementawn commented on arches/app/templates/index-revolution.htm
I'm not sure that we should be maintaining the 'old' version of the index page like this. Need to provide backwards compatibility by including the necessary libraries in `arches/app/media/plugins`, but I think we can get rid of this file and just keep the index page with the updated slider. What are your thoughts @apeters

2023-10-31 23:20 UTC, johnatawnclementawn commented on arches/app/media/css/index.css
To prevent breaking existing index pages, can you add `@import url(./index-slider-legacy.css);` to the beginning of this file?

2023-11-01 14:33 UTC, phudson-he commented
@johnatawnclementawn Your previous comments resolved by commit 97eb228

2023-11-01 17:46 UTC, johnatawnclementawn approved these changes
Looks great! Thanks @phudson-he

2023-11-01 17:46 UTC, merged