Adds generic search thumbnail retrieval
archesproject/arches pull request #10266
Opened 2023-11-13 21:30 UTC by aarongundel

Adds search thumbnails - to be implemented at the project level.

2023-11-14 01:14 UTC, chiatt requested changes
This looks great. Just a couple unused imports to remove and I think adding that setting to the project template would be nice.

2023-11-14 23:06 UTC, aarongundel commented on arches/settings.py
> +SEARCH_THUMBNAILS = False
done

2023-11-14 23:06 UTC, aarongundel commented on arches/app/utils/search_thumbnail_fetcher_factory.py
> +from logging import Logger
it is used on line 17

2023-11-15 23:24 UTC, chiatt commented on arches/app/utils/search_thumbnail_fetcher_factory.py
> +from logging import Logger
On 17 you are using 'logging' which is defined on line 8 imported from line 2.  Logger itself is unused.

2023-11-27 23:58 UTC, chiatt approved these changes

2023-11-28 00:24 UTC, merged