add accessibility fixes for the public facing side of Arches
archesproject/arches pull request #10265
Opened 2023-11-13 20:06 UTC by apeters

to test, make sure to do a yarn.install first

2023-11-15 17:47 UTC, chiatt requested changes
The notification icon is no longer green:
![image](https://github.com/archesproject/arches/assets/1877663/41242bea-52f6-4f7d-931e-e5ca258d1f69)

2023-11-15 18:15 UTC, chiatt requested changes
Layer visibility slider covers layer name
![image](https://github.com/archesproject/arches/assets/1877663/9c353e59-1343-460b-8a78-c3803d3f115f)

2023-11-15 18:33 UTC, chiatt requested changes
I'm unable to enter text into the resource-instance dropdown input. This prevents filtering needed to get to the 'Create New Resource' option at the bottom of the list.

Also, when trying to move through AFS workflow steps that use select2, errors occur preventing the workflow from advancing properly.

![image](https://github.com/archesproject/arches/assets/1877663/37b64ee4-9933-4437-aec5-a14b5d005650)

2023-11-15 19:37 UTC, chrabyrd commented
The resource-instance dropdown does not show a dropdown arrow. This was tested with advanced-search.

<img width="670" alt="Screenshot 2023-11-15 at 11 34 33 AM" src="https://github.com/archesproject/arches/assets/9162695/4cd7f853-a977-4976-94a2-43dddbb28c09">

However, I was able to enter text in the resource-instance-dropdown input.

2023-11-15 19:39 UTC, chrabyrd commented
There is a double-border on resource instance dropdowns when no results are returned

<img width="670" alt="Screenshot 2023-11-15 at 11 38 25 AM" src="https://github.com/archesproject/arches/assets/9162695/fbb586f1-ed59-4054-a57f-8d17e4591ee4">

2023-11-15 19:44 UTC, chrabyrd commented on arches/app/media/js/bindings/select2-query.js
> +                        console.log(newVal);
errant `console.log`

2023-11-15 19:47 UTC, chrabyrd commented
> Also, when trying to move through AFS workflow steps that use select2, errors occur preventing the workflow from advancing properly.
> 
> ![image](https://user-images.githubusercontent.com/1877663/283213963-37b64ee4-9933-4437-aec5-a14b5d005650.png)

I can verify this error, and it appears in the editor as well.

2023-11-15 20:17 UTC, chrabyrd commented
The concept dropdown in RDM does not appear to be functional

<img width="743" alt="Screenshot 2023-11-15 at 12 16 19 PM" src="https://github.com/archesproject/arches/assets/9162695/fc5eec50-ae76-40a3-a8c2-c090a0fc5b96">

2023-11-15 20:23 UTC, chrabyrd commented
When a dropdown loads, it loses its placeholder text:

http://g.recordit.co/41hI7ORsDJ.gif

2023-11-15 20:30 UTC, chrabyrd commented
manifest manager dropdown does not close when item is selected

http://g.recordit.co/wNnRrm5i6y.gif

2023-11-15 20:33 UTC, chrabyrd commented
attempting to clear the entry in the manifest manager results in error:

http://g.recordit.co/vAwNARAdO1.gif

```
Uncaught TypeError: Cannot read properties of undefined (reading 'id')
```

2023-11-15 20:36 UTC, chrabyrd commented
Manifest manager loads image service without hitting the button or saving the tile:

http://g.recordit.co/6V2uvNUF2X.gif

2023-11-15 20:38 UTC, chrabyrd commented
cannot clear resource-instance-select in the resource editor:

http://g.recordit.co/79wdNW64zL.gif

2023-11-15 20:45 UTC, chrabyrd commented
The dropdown in the multi-tile-step is no longer functional:

<img width="1410" alt="Screenshot 2023-11-15 at 12 44 55 PM" src="https://github.com/archesproject/arches/assets/9162695/ff84a223-20c1-461c-a80a-117e9c1cfbd5">

2023-11-16 00:54 UTC, apeters commented
> The concept dropdown in RDM does not appear to be functional and has no placeholder text
> 
> <img alt="Screenshot 2023-11-15 at 12 16 19 PM" width="743" src="https://user-images.githubusercontent.com/9162695/283237179-fc5eec50-ae76-40a3-a8c2-c090a0fc5b96.png">

fixed by > ae14a1f

2023-11-16 00:57 UTC, apeters commented
> manifest manager dropdown does not close when item is selected
> 
> http://g.recordit.co/wNnRrm5i6y.gif

> attempting to clear the entry in the manifest manager results in error:
> 
> http://g.recordit.co/vAwNARAdO1.gif
> 
> ```
> Uncaught TypeError: Cannot read properties of undefined (reading 'id')
> ```


both fixed by > [2b12e66](https://github.com/archesproject/arches/pull/10265/commits/2b12e66be4d08e8d74d22eaf60871bad40f68e43)

2023-11-16 01:01 UTC, apeters commented
> Manifest manager loads image service without hitting the button or saving the tile:
> 
> http://g.recordit.co/6V2uvNUF2X.gif

this operates the same way in dev/7.5.x

2023-11-16 01:21 UTC, apeters commented
> The resource-instance dropdown does not show a dropdown arrow. This was tested with advanced-search.
> 
> <img alt="Screenshot 2023-11-15 at 11 34 33 AM" width="670" src="https://user-images.githubusercontent.com/9162695/283228290-4cd7f853-a977-4976-94a2-43dddbb28c09.png">
> However, I was able to enter text in the resource-instance-dropdown input.

fixed by: [1cfab6b](https://github.com/archesproject/arches/pull/10265/commits/1cfab6b00238e090dbb664ec1a74ab36ad1e582c)

2023-11-16 01:30 UTC, apeters commented
> There is a double-border on resource instance dropdowns when no results are returned
> 
> <img alt="Screenshot 2023-11-15 at 11 38 25 AM" width="670" src="https://user-images.githubusercontent.com/9162695/283228882-fbb586f1-ed59-4054-a57f-8d17e4591ee4.png">

fixed by: [07f73ff](https://github.com/archesproject/arches/pull/10265/commits/07f73ffb7c0944dd785b27dbf9d4e1b2f97a2b23)

2023-11-16 01:35 UTC, apeters commented on arches/app/media/js/bindings/select2-query.js
> +                        console.log(newVal);
fixed by: [ad54fbc](https://github.com/archesproject/arches/pull/10265/commits/ad54fbc842ee7a69f0cbd9214479ec42078adbf9)

2023-11-16 03:29 UTC, apeters commented
> When a dropdown loads, it loses its placeholder text:
> 
> http://g.recordit.co/41hI7ORsDJ.gif



> cannot clear resource-instance-select in the resource editor:
> 
> http://g.recordit.co/79wdNW64zL.gif

both fixed by: [880ef0f](https://github.com/archesproject/arches/pull/10265/commits/880ef0fdd82a59c1b89f676ca11f6c17681efa3f)

2023-11-16 03:32 UTC, apeters commented
> The notification icon is no longer green: ![image](https://user-images.githubusercontent.com/1877663/283203562-41242bea-52f6-4f7d-931e-e5ca258d1f69.png)

@chiatt this issue currently exists in dev/7.5.x

2023-11-16 04:58 UTC, apeters commented
> The notification icon is no longer green: ![image](https://user-images.githubusercontent.com/1877663/283203562-41242bea-52f6-4f7d-931e-e5ca258d1f69.png)

fixed by: [06fb7f4](https://github.com/archesproject/arches/pull/10265/commits/06fb7f4f36a444d02bb230508f26d9e6100e1f3a)

2023-11-16 18:03 UTC, apeters commented
@chiatt this issue currently exists in dev/7.5.x



> Layer visibility slider covers layer name ![image](https://user-images.githubusercontent.com/1877663/283210101-9c353e59-1343-460b-8a78-c3803d3f115f.png)

2023-11-17 23:15 UTC, chrabyrd commented
The first step of the project collection workflow fails. This is a generic workflow step.

<img width="1380" alt="Screenshot 2023-11-17 at 3 12 55 PM" src="https://github.com/archesproject/arches/assets/9162695/287b026c-7ccb-4a1e-acbf-0173285562f7">

error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'resourceId')
    at eval (resource-instance-select.js:510:38)
```

config:
```
                            componentConfigs: [
                                {
                                    componentName: 'resource-instance-select-widget',
                                    uniqueInstanceName: 'select-project', /* unique to step */
                                    parameters: {
                                        graphids: [
                                            '0b9235d9-ca85-11e9-9fa2-a4d18cec433a'/* Project */
                                        ],
                                    },
                                },
                            ], 
```

2023-11-17 23:18 UTC, chrabyrd commented
This is project-level, but the `Show Workflow Help` dropdown in the init-workflow plugin fails. Are there changes that need to be made to any select2Configs when migrating to select-woo?

2023-11-17 23:24 UTC, chrabyrd commented
The fonts in the account section of the user profile manager are wrong. The values are small and the labels are big:

<img width="662" alt="Screenshot 2023-11-17 at 3 22 29 PM" src="https://github.com/archesproject/arches/assets/9162695/473699ad-4d29-4d97-be8c-fa80992639ab">

2023-11-17 23:30 UTC, chrabyrd commented
nit: z-index conflict between dropdown menu and sidebar options

<img width="690" alt="Screenshot 2023-11-17 at 3 29 44 PM" src="https://github.com/archesproject/arches/assets/9162695/65f07552-c0b2-4a33-8f71-7e68b3cafc02">

2023-11-17 23:54 UTC, chrabyrd commented
Still noticing some of the behavior that when a dropdown loads it loses its placeholder text:

http://g.recordit.co/9oOhQddKiK.gif

2023-11-17 23:58 UTC, chrabyrd commented
concept-select does not retain selection

http://g.recordit.co/ixpQG9Pxvj.gif

2023-11-21 18:00 UTC, apeters commented
> I'm unable to enter text into the resource-instance dropdown input. This prevents filtering needed to get to the 'Create New Resource' option at the bottom of the list.
> 
> Also, when trying to move through AFS workflow steps that use select2, errors occur preventing the workflow from advancing properly.
> 
> ![image](https://user-images.githubusercontent.com/1877663/283213963-37b64ee4-9933-4437-aec5-a14b5d005650.png)

fixed by https://github.com/archesproject/arches/pull/10265/commits/dc3827bb9ac503527a62ab01b282136754e489f1

2023-11-21 18:04 UTC, apeters commented
> The first step of the project collection workflow fails. This is a generic workflow step.
> 
> <img alt="Screenshot 2023-11-17 at 3 12 55 PM" width="1380" src="https://user-images.githubusercontent.com/9162695/283953640-287b026c-7ccb-4a1e-acbf-0173285562f7.png">
> error:
> 
> ```
> Uncaught TypeError: Cannot read properties of undefined (reading 'resourceId')
>     at eval (resource-instance-select.js:510:38)
> ```
> 
> config:
> 
> ```
>                             componentConfigs: [
>                                 {
>                                     componentName: 'resource-instance-select-widget',
>                                     uniqueInstanceName: 'select-project', /* unique to step */
>                                     parameters: {
>                                         graphids: [
>                                             '0b9235d9-ca85-11e9-9fa2-a4d18cec433a'/* Project */
>                                         ],
>                                     },
>                                 },
>                             ], 
> ```

fixed in the latest

2023-11-21 21:07 UTC, apeters commented
> Still noticing some of the behavior that when a dropdown loads it loses its placeholder text:
> 
> http://g.recordit.co/9oOhQddKiK.gif

I can't reproduce this

2023-11-21 21:14 UTC, chiatt commented
> > Still noticing some of the behavior that when a dropdown loads it loses its placeholder text:
> > http://g.recordit.co/9oOhQddKiK.gif
> 
> I can't reproduce this

I see the same behavior, but only the first time the card is loaded. Using the Person model in AFS, if I select Project Team, the input becomes disabled and then reenabled without the placeholder. Select a different card and then back to Project Team and the widget loads fine.

2023-11-21 21:15 UTC, chiatt approved these changes

2023-11-21 21:22 UTC, chiatt requested changes
Very strange, but I'm unable to enter a string with a space in it in the relationship creator UI. 

To reproduce, create a new resource in the resource-instance widget.

![image](https://github.com/archesproject/arches/assets/1877663/b1f6d205-92ce-4652-8d3f-2f7de5da69ef)

Then try to enter a string with a space in it and the cursor disappears from the widget and appears in the upper left corner of the page.

![image](https://github.com/archesproject/arches/assets/1877663/22674ff4-5e7c-4155-b813-1b5e81c7c05c)

2023-11-21 21:35 UTC, apeters commented
> concept-select does not retain selection
> 
> http://g.recordit.co/ixpQG9Pxvj.gif

fixed in [613207c](https://github.com/archesproject/arches/pull/10265/commits/613207c3508a9f8febfb0e15e01e50b1160b0b63)

2023-11-21 21:42 UTC, apeters commented
> The fonts in the account section of the user profile manager are wrong. The values are small and the labels are big:
> 
> <img alt="Screenshot 2023-11-17 at 3 22 29 PM" width="662" src="https://user-images.githubusercontent.com/9162695/283954733-473699ad-4d29-4d97-be8c-fa80992639ab.png">

fixed by [14b7f86](https://github.com/archesproject/arches/pull/10265/commits/14b7f86160c4b8cb421c4692365d9d0e70bb7f51)

2023-11-21 22:14 UTC, chiatt approved these changes

2023-11-21 23:08 UTC, chrabyrd commented
nit: There is no loading UX for dropdowns. When there are several on a page, no results will display until all dropdowns have finished loading. If possible we should include loading UX

http://g.recordit.co/pMWYxQJHql.gif

2023-11-21 23:16 UTC, chrabyrd commented
The search results details component pushes the top bar buttons and time filter/saved searches buttons off the page

<img width="1543" alt="Screenshot 2023-11-21 at 3 14 52 PM" src="https://github.com/archesproject/arches/assets/9162695/49319b9b-9adb-4448-abed-d954c5d6c282">

2023-11-21 23:18 UTC, chrabyrd commented
View search-result-details with any advanced search compresses the search results sidebar.

<img width="1543" alt="Screenshot 2023-11-21 at 3 17 03 PM" src="https://github.com/archesproject/arches/assets/9162695/4fbc1335-bcfc-4232-9c16-0109eaa37610">

2023-11-21 23:20 UTC, chrabyrd commented
The resource instance dropdown in the resource editor list page does not work. Also nit, the `Find` and `Resources` buttons have different font sizes.

<img width="1543" alt="Screenshot 2023-11-21 at 3 19 28 PM" src="https://github.com/archesproject/arches/assets/9162695/28c044aa-cf60-46ec-9cc3-ea276f4bdf54">

2023-11-21 23:24 UTC, chrabyrd commented
Sometimes when loading concept-multiselect components, their options will be listed twice:

http://g.recordit.co/X4awBOjlI5.gif

I am able to consistently reproduce this via creating a new `Instrument` resource in the resource editor.

2023-11-21 23:29 UTC, chrabyrd commented
deleting a `resource-instance-select` selection does not update the card tree

http://g.recordit.co/4RMKbKNLOv.gif

2023-11-21 23:40 UTC, chrabyrd requested changes
Some of the above points are nits and can be ignored, but the duplication of values in concept-multiselect appear to be a serious issue.

2023-11-22 01:09 UTC, chiatt requested changes
In the Upload XY Data workflow, the iiif gallery is pushed down below the bottom of the page.
![image](https://github.com/archesproject/arches/assets/1877663/39eb5c1b-e82a-49bf-9df9-e42b6f8d4904)

Also, I'm not able to select importers in the XY Loader step.

![image](https://github.com/archesproject/arches/assets/1877663/2a91af57-dd7e-48a4-a105-bebe29607d91)

2023-11-22 04:25 UTC, apeters commented
> The resource instance dropdown in the resource editor list page does not work. Also nit, the `Find` and `Resources` buttons have different font sizes.
> 
> <img alt="Screenshot 2023-11-21 at 3 19 28 PM" width="1543" src="https://user-images.githubusercontent.com/9162695/284744689-28c044aa-cf60-46ec-9cc3-ea276f4bdf54.png">

this doesn't work either in dev/7.5.x  (it's also a chosen dropdown which I didn't touch)

2023-11-22 05:51 UTC, apeters commented
> The search results details component pushes the top bar buttons and time filter/saved searches buttons off the page
> 
> <img alt="Screenshot 2023-11-21 at 3 14 52 PM" width="1543" src="https://user-images.githubusercontent.com/9162695/284744109-49319b9b-9adb-4448-abed-d954c5d6c282.png">



> View search-result-details with any advanced search compresses the search results sidebar.
> 
> <img alt="Screenshot 2023-11-21 at 3 17 03 PM" width="1543" src="https://user-images.githubusercontent.com/9162695/284744313-4fbc1335-bcfc-4232-9c16-0109eaa37610.png">

fixed by [05a418d](https://github.com/archesproject/arches/pull/10265/commits/05a418d3979db0f69ca58958bf40ca5e89b81f2f)

2023-11-22 06:11 UTC, apeters commented
> In the Upload XY Data workflow, the iiif gallery is pushed down below the bottom of the page. ![image](https://user-images.githubusercontent.com/1877663/284758524-39eb5c1b-e82a-49bf-9df9-e42b6f8d4904.png)
> 
> Also, I'm not able to select importers in the XY Loader step.
> 
> ![image](https://user-images.githubusercontent.com/1877663/284758864-2a91af57-dd7e-48a4-a105-bebe29607d91.png)

fixed by [3388b94](https://github.com/archesproject/arches/pull/10265/commits/3388b94b876837f1e08e8a7839bf181db592021d)

2023-11-22 06:14 UTC, apeters commented
> Also, I'm not able to select importers in the XY Loader step.
> 
> ![image](https://user-images.githubusercontent.com/1877663/284758864-2a91af57-dd7e-48a4-a105-bebe29607d91.png)

this is probably because the select2 configs are now outdated.  If we fix this now before we push the accessibility branch then this will break for everyone.  I will have to stage a fix on the AFS repo, to be applied after the accessibility branch gets merged in.

2023-11-23 01:14 UTC, apeters commented
> deleting a `resource-instance-select` selection does not update the card tree
> 
> http://g.recordit.co/4RMKbKNLOv.gif

this is an issue in dev/7.5.x

2023-11-28 00:47 UTC, apeters commented
> Sometimes when loading concept-multiselect components, their options will be listed twice:
> 
> http://g.recordit.co/X4awBOjlI5.gif
> 
> I am able to consistently reproduce this via creating a new `Instrument` resource in the resource editor.

fixed by [d7b8b7c](https://github.com/archesproject/arches/pull/10265/commits/d7b8b7cb78062121875090bda7a87a8b30bef2ff)

2023-11-28 21:38 UTC, chrabyrd commented
nit: some concepts show `&nbsp;` 

<img width="1543" alt="Screenshot 2023-11-28 at 1 37 02 PM" src="https://github.com/archesproject/arches/assets/9162695/ffc54a31-34f8-4119-9fd7-9a5adc3c05f6">

2023-11-28 21:51 UTC, chrabyrd commented
Overall lgtm -- there's still several AFS-level issues but since they've been mentioned already and will be solved in their own ticket I won't repeat them here. 

I appreciate the level of complexity here and thanks for working with us to stamp out all the bugs we can find before merge 👍

2023-11-28 21:51 UTC, chrabyrd approved these changes

2023-11-29 00:20 UTC, apeters commented
> nit: some concepts show `&nbsp;`
> 
> <img alt="Screenshot 2023-11-28 at 1 37 02 PM" width="1543" src="https://private-user-images.githubusercontent.com/9162695/286407363-ffc54a31-34f8-4119-9fd7-9a5adc3c05f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMTY5OTQsIm5iZiI6MTcwMTIxNjY5NCwicGF0aCI6Ii85MTYyNjk1LzI4NjQwNzM2My1mZmM1NGEzMS0zNGY4LTQxMTktOWZkNy05YTVhZGMzYzA1ZjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjlUMDAxMTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGQ5YWQzMGY4MGQ3Njg5NWVmZDNkMzA1ZTJhMTQ4YTRhMWY4OWM3MmMxY2Q4ZGZhYjNmZGIwOGViY2VjOWQ4YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7myJs1UDZHXWOEIpr9IMmEmWnwArC6sUl3Tsd66J05s">

fixed in [1d23fb6](https://github.com/archesproject/arches/pull/10265/commits/1d23fb6bc281cd726d7e6b6381cdef29a8da49f9)

2023-11-30 22:45 UTC, chrabyrd commented
nit: RDM dropdown does not have placeholder text

<img width="1482" alt="Screenshot 2023-11-30 at 2 44 42 PM" src="https://github.com/archesproject/arches/assets/9162695/865a0870-c753-42a5-9ae3-14045f0552c7">

2023-11-30 22:51 UTC, chrabyrd commented
nit: clearing a value from dropdowns opens the dropdown

http://g.recordit.co/1Z2TqqrkBA.gif

2023-11-30 22:54 UTC, chrabyrd commented
nit: concept-multiselect values are not properly aligned

<img width="616" alt="Screenshot 2023-11-30 at 2 52 36 PM" src="https://github.com/archesproject/arches/assets/9162695/19f33712-76ac-47b0-a351-db9ba2fd14ab">

2023-11-30 23:00 UTC, chrabyrd commented
All of the above are nits, I haven't found anything that would block merging in these changes 👍

2023-11-30 23:42 UTC, apeters commented
> nit: RDM dropdown does not have placeholder text
> 
> <img alt="Screenshot 2023-11-30 at 2 44 42 PM" width="1482" src="https://private-user-images.githubusercontent.com/9162695/287090828-865a0870-c753-42a5-9ae3-14045f0552c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzODcwMTMsIm5iZiI6MTcwMTM4NjcxMywicGF0aCI6Ii85MTYyNjk1LzI4NzA5MDgyOC04NjVhMDg3MC1jNzUzLTQyYTUtOWFlMy0xNDA0NWYwNTUyYzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMzBUMjMyNTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTY2MzUzOGRmMWY5NGRiNDU2ZTFiNGQyZGMzYzQxM2RkODAwNDg4YzIxYTUxNjljOGNkODI1NmM2ZDFhOGZmMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2nvIvy-vtcfq25KlZBn02Oqu-I5l6yMZSPRPGpwwcpc">

fixed in [99122d5](https://github.com/archesproject/arches/pull/10265/commits/99122d54aa3ff1c7becc714a23ccf9437ca720c3)

2023-12-01 00:59 UTC, apeters commented
> nit: the larger text in the text/rich text widgets can push the copy/edit/delete buttons out of alignment.
> 
> Additional question -- I noticed that throughout the system _some_ text is larger but not all text. Take the card in the image below for instance. Is this intentional? What's the rule of thumb here?
> 
> <img alt="Screenshot 2023-11-30 at 2 35 21 PM" width="2000" src="https://private-user-images.githubusercontent.com/9162695/287089521-b70b512d-53c0-4c58-908c-4d35fab33096.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzOTIxNTgsIm5iZiI6MTcwMTM5MTg1OCwicGF0aCI6Ii85MTYyNjk1LzI4NzA4OTUyMS1iNzBiNTEyZC01M2MwLTRjNTgtOTA4Yy00ZDM1ZmFiMzMwOTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDFUMDA1MDU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWQ1OTVlZDE5NDk4NzU5MjhkMGI5Y2U0ZGVkOWYwYTA0NzYzZWUxZTUxN2M0OTA4YjdlZWVjM2FjZmViMTJhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9Bm4Hwokyb45xc7GiaIE-Hcngu4M_Bv9iU0N3ala2mc">

@chrabyrd I'm not seeing this on my site.  Can you tell what style it's using?

2023-12-01 01:33 UTC, apeters commented
@chrabyrd if there is really no more to QA and it's only small styling issues, then I'd say we shouldn't block testing and merge this into core.

2023-12-01 01:35 UTC, chrabyrd commented
@apeters agreed, already approved the changes a few iterations ago

2023-12-02 00:24 UTC, merged