Replace workflow slugs with workflow names in incomplete workflows modal #10496
archesproject/arches pull request #10524
Opened 2024-01-13 03:10 UTC by ryan86

Replace workflow slug with workflow name in incomplete workflow modal #10496

2024-01-13 03:11 UTC, ryan86 commented
Unclear if this should be targeting 7.5 or 7.6

2024-01-15 16:02 UTC, jacobtylerwalls requested changes

2024-01-15 19:52 UTC, jacobtylerwalls commented on arches/app/views/api.py
> +            plugin.slug: plugin.name
Oh sorry, one more thing. Could you change `plugin.slug` to `plugin.componentname`? We seem to be getting lucky that they're always the same, but the code I linked above shows that `componentname` is being used for the source of truth.

2024-01-15 19:54 UTC, jacobtylerwalls commented on arches/app/views/api.py
> +            plugin.slug: plugin.name
Unless it's a bug that we're using `componentname` instead of `slug` in that place...

2024-01-15 20:08 UTC, jacobtylerwalls commented on arches/app/views/api.py
> +            plugin.slug: plugin.name
Thanks, this is great, I opened #10526 for the follow-up

2024-01-15 20:17 UTC, jacobtylerwalls approved these changes

2024-01-15 20:17 UTC, merged