Workflow History doesn't reload every tile #10538
archesproject/arches pull request #10539
Opened 2024-01-18 23:00 UTC by teenorth

### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

Description included in issue.

### Issues Solved

#10538 

### Checklist

-   [ ] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: 
*   Found by: @teenorth
*   Tested by: @teenorth
*   Designed by: @

### Further comments

2024-01-18 23:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/archesproject/arches?pullRequest=10539) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/archesproject/arches?pullRequest=10539) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/archesproject/arches?pullRequest=10539) it.</sub>

2024-01-23 13:47 UTC, jacobtylerwalls requested changes
Thanks for the fix and helpful diagnosis!

I missed these because I happened to be testing with workflows that had at most one card per step. Great catch.

Thanks for finding a solution that doesn't present a backwards-compatibility problem. I tested with a workflow created on 7.5.0 and it restores on this branch just fine. (Tested with Arches for Science.)

This is a bug in a new feature, so I think we should target 7.5. Could you rebase on dev/7.5.x? There's likely to be a 7.5.1 release on Thursday, so I would very much like to get this in before then. Thanks.

2024-01-23 19:36 UTC, jacobtylerwalls approved these changes
Thanks for the updates!

2024-01-23 19:38 UTC, teenorth commented
Sure! I've doing quite a lot of work around the workflows lately and I'm currently setting up a reload/edit/open previous workflow for a resource. I had a working version on an older version of Arches that used the local storage but it required a complex setup function. Having the workflow data stored in the database is going to be a massive time save and smoother implementation!

2024-01-23 19:45 UTC, merged