Add a generic etl celery task for custom module, #10573
archesproject/arches pull request #10574
Opened 2024-02-01 19:27 UTC by njkim

### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

### Issues Solved

#

### Checklist

-   [ ] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: 
*   Found by: @ 
*   Tested by: @ 
*   Designed by: @ 

### Further comments

2024-02-01 22:35 UTC, apeters requested changes

2024-02-01 22:35 UTC, apeters commented on arches/app/tasks.py
> +        import_class().run_load_task(**kwargs)
here you can then use the method I defined in the previous comment.
``` self.run_task(module_name=import_module, class_name=import_class, method_to_run="run_load_task", **kwargs) ```

2024-02-02 22:18 UTC, njkim commented on arches/app/tasks.py
> +
yep, this is great. thanks.

2024-02-23 02:10 UTC, apeters approved these changes
looks good!

2024-02-23 02:11 UTC, merged