10529 adv search list operators
archesproject/arches pull request #10610
Opened 2024-02-14 23:14 UTC by whatisgalen

### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

### Issues Solved

#

### Checklist

-   [ ] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: 
*   Found by: @ 
*   Tested by: @ 
*   Designed by: @ 

### Further comments

2024-03-28 06:42 UTC, whatisgalen commented on arches/app/datatypes/concept_types.py
> +                field_name = "tiles.data.%s" % (str(node.pk))
requested change in latest

2024-03-28 06:46 UTC, whatisgalen commented on arches/app/datatypes/concept_types.py
> +    def append_in_list_search_filters(self, value, node, query, request, match_any=True):
requested change in latest

2024-03-28 06:46 UTC, whatisgalen commented on arches/app/datatypes/concept_types.py
> +                    if match_any:
requested change in latest

2024-03-28 06:48 UTC, whatisgalen reviewed
all requested changes in latest

2024-04-05 18:25 UTC, chiatt requested changes

2024-04-08 19:30 UTC, chiatt approved these changes

2024-04-08 19:30 UTC, merged