Provide hooks to allow customization of resource instance ES documents
archesproject/arches pull request #10999
Opened 2024-06-04 19:11 UTC by bferguso

### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

Allows for customization of the ES resources index so that additional documents can be associated with a resource to support additional search values.

### Issues Solved

Closes #10987 

### Checklist

-   I targeted one of these branches:
    - [x] dev/7.6.x (under development): features, bugfixes not covered below
    - [ ] dev/7.5.x (main support): regressions, crashing bugs, security issues, major bugs in new features
    - [ ] dev/6.2.x (extended support): major security issues, data loss issues
-   [ ] I added a changelog in arches/releases
-   [ ] I submitted a PR to arches-docs (if appropriate)
-   [ ] Unit tests pass locally with my changes
-   [ ] I added tests that prove my fix is effective or that my feature works
-   [ ] My test fails on the target branch

#### Accessibility Checklist
n/a - Currently no front end to this PR

[Developer Guide](https://arches.readthedocs.io/en/stable/developing/advanced/accessibility/)

| Topic            | Changed | Retested |
| ---------------- | ------- | -------- |
| Color contrast   |         |          |
| Form fields      |         |          |
| Headings         |         |          |
| Links            |         |          |
| Keyboard         |         |          |
| Responsive Design|         |          |
| HTML validation  |         |          |
| Screen reader    |         |          |

#### Ticket Background
*   Sponsored by: Self Funded
*   Found by: @bferguso
*   Tested by: @bferguso
*   Designed by: @bferguso

### Further comments
This is an initial PR for discussion to see if this strategy is acceptable for inclusion in arches core. Additional tests/documentataion/etc will be added if it is to be accepted. At a high level this change:
1. adds a hook to `search/mappings.py` to allow additional ES documents to be associated with resource instances
2. adds a hook to `models/resource.py` to allow additional data to be added to the ES documents associated with the resource instance
3. adds a hook to `search/components/term_filter.py` to allow the documents added by (2) to be searched.

The above behaviour can be implemented by providing a class that implements 3 methods, one for each of the functions above. Currently the class is configured in `settings.py`. If the class isn't configured this change is a NOOP.

2024-06-12 20:40 UTC, whatisgalen commented
just adding this comment for posterity:
Bret and I discussed this PR in the added context of #10807 and noted that it might be a better approach to move the logic in the Resource Proxy model (concerning what gets sent to the indexing/document handling methods from the resource) into its own place so that it can be more easily extended or customized.

2024-06-13 14:43 UTC, bferguso commented
Looking into what @whatisgalen and I discussed - we'd still need a way to be able to configure the external utility classes within core arches. The `term_filter.py` is configured within the database so that can easily be overridden, but extending the functionality of `arches.app.search.mappings.prepare_search_index` and `arches.app.models.resource.Resource.get_documents_to_index` would (as far as I can see) need to be configured to be able to override that functionality. It would still likely be a better way to allow customization of that functionality but needs some thought.

2024-08-13 19:31 UTC, chiatt requested changes
This looks like a nice start, but I'm getting this error when I add the example class to my project and try to save a tile:
```  
File "/arches/app/models/resource.py", line 648, in get_documents_to_index
    Resource.custom_search_class.add_search_terms(self, document, terms)
  File "/disco/search_indexes/custom_resource_search.py", line 12, in add_search_terms
    document[CustomResourceSearchValue.custom_search_path].append(
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'custom_values'
```

2024-08-16 23:35 UTC, chiatt requested changes

2024-08-19 00:01 UTC, bferguso commented on arches/install/arches-templates/project_name/settings.py-tpl
> +# See arches.app.util.custom_resource_search.py for example
Sorry- I thought I'd changed that. Updated to reference the test class.

2024-08-19 00:14 UTC, chiatt approved these changes

2024-08-29 22:52 UTC, bferguso commented
@apeters - I've refactored as per our conversation today. Feel free to have a look.

2024-08-30 04:04 UTC, whatisgalen commented
@bferguso apologies if this is a naive question, but is there any reason the name `get_custom_search_path` is preferred over, say `get_custom_mapping_property`? I know there's not a ton we can do about how overloaded the word "search" is, but I was initially tripped up that the class is called a `CustomResourceSearch` because I don't think it really contains search logic, it's more just making sure that some custom mapping property gets both indexed and searched on, right?

2024-09-04 14:45 UTC, bferguso commented
> @bferguso apologies if this is a naive question, but is there any reason the name `get_custom_search_path` is preferred over, say `get_custom_mapping_property`? I know there's not a ton we can do about how overloaded the word "search" is, but I was initially tripped up that the class is called a `CustomResourceSearch` because I don't think it really contains search logic, it's more just making sure that some custom mapping property gets both indexed and searched on, right? And if true, what if it was called `CustomMappingHook`? Again, apologies if all this has already been discussed.

@whatisgalen - This actually does contain search logic as well. There are 3 parts of the funcitonality namely:
1. a section that adds the ES document configuration during ES index build, 
2. one part that populates the ES document as part of the resource save, and 
3. one that modifies the DSL to use the additional portion of the ES document. 
Without the change in search DSL (3) the additional portion of the ES document would be ignored. The reason I used `get_custom_search_path` is because it's part of the JSON document, which may be a top level value, but doesn't need to be.

2024-09-04 19:01 UTC, whatisgalen commented
Given that the `CustomResourceSearch` class is mutating search query DSL, that part of it (`custom_search_class.add_search_filter`) seems redundant to the functionality of individual search components. Since #10807 got merged, a developer has complete freedom in customizing how a search operates at every point, including mutating query DSL. In that context, I think what's novel about your PR are the hooks for indexing and `add_search_terms` (which I think are excellent improvements, btw). 

In looking at how `custom_search_class.add_search_filter` is used in `TermFilter`, I could just as easily see how a different component (e.g. `ResourceTypeFilter`, `TimeFilter`, etc.) would want to also leverage custom mappings. Given how open-ended the utilization of custom mappings could be, I would expect most developers to create their own custom search components to work with custom mappings.

So in short, my thought is: let's keep the parts of this that hook into indexing and ES document mutation, and leave some example/guidance on how to interact with a custom mapping class from a search component.


For example in `search/components/base.py` I could imagine this generic method to be overridden/implemented by a custom component:
```.py
class BaseSearchFilter:
    def __init__(self, request=None, user=None, componentname=None):
        self.request = request
        self.user = user
        self.componentname = componentname

    def append_dsl(self, search_query_object, **kwargs):
        """
        used to append ES query dsl to the search request
        """

        pass
    
    ...
    
    def handle_custom_mapping(self, **kwargs):
        """
        logic to handle custom mappings
        
        for ex:

        from arches.app.search.custom_mapping import CustomMappingFactory
        for (
            custom_mapping_class
        ) in CustomMappingFactory.get_custom_mapping_classes():
            custom_mapping_class.add_search_filter(search_query, term)
        """
        
        pass
```

That way if you had a custom mapping A for `TermFilter` and a custom mapping B for `TimeFilter`, not only could you apply specific logic for each, but you could implement and call `handle_custom_mapping` from any of the other `BaseFilter` class methods, e.g. `append_to_dsl`, `post_search_hook`, `execute_query`, etc.

2024-09-04 21:06 UTC, bferguso commented
@whatisgalen  - Sounds like this should be rolled into your search component PR then. I think a farily tight coupling between the ES document configuration, resource->ES mapping, and DSL manipulation makes it quite modular. I suppose if we were to add the hooks to the `models/resource.py` and `components/mapping.py` in your componentization implementation that could also satisfy what I was trying to achieve here.

2024-09-11 00:33 UTC, apeters commented
@bferguso I think what this means is that we just need to remove all the edits to `term-filter.py`.

2024-09-11 01:43 UTC, whatisgalen requested changes

2024-09-11 01:43 UTC, whatisgalen commented on arches/app/search/custom_resource_search.py
I think it would be good to rename this file to `custom_mapping_hook.py`

2024-09-11 01:43 UTC, whatisgalen commented on arches/app/search/custom_resource_search.py
> +    def get_custom_search_path():
```suggestion
    def get_custom_mapping_property():
```

2024-09-11 01:43 UTC, whatisgalen commented on arches/app/search/custom_resource_search.py
> +class CustomResourceSearch:
```suggestion
class CustomMappingHook:
```

2024-09-11 01:43 UTC, whatisgalen commented on arches/app/search/custom_resource_search.py
> +    custom_search_path = "custom_values"
```suggestion
    custom_mapping_property = "custom_values"
```

2024-09-11 01:43 UTC, whatisgalen commented on arches/app/search/custom_resource_search.py
> +        return CustomResourceSearch.custom_search_path
```suggestion
        return CustomMappingHook.custom_mapping_property
```

2024-09-11 01:43 UTC, whatisgalen commented on arches/app/search/custom_resource_search.py
> +    def get_custom_search_config():
```suggestion
    def get_custom_mapping():
```

2024-09-11 01:43 UTC, whatisgalen commented on arches/app/search/mappings.py
> +from arches.app.search.custom_resource_search import CustomResourceSearchFactory
```suggestion
from arches.app.search.custom_mapping_hook import CustomMappingHookFactory
```

2024-09-11 01:43 UTC, whatisgalen commented on arches/app/search/custom_resource_search.py
> +class CustomResourceSearchFactory:
```suggestion
class CustomMappingHookFactory:
```

2024-09-11 01:43 UTC, whatisgalen commented on arches/app/search/custom_resource_search.py
> +                for classname in settings.CUSTOM_SEARCH_CLASSES
```suggestion
                for classname in settings.CUSTOM_MAPPING_HOOKS
```

2024-09-11 01:43 UTC, whatisgalen commented on arches/app/search/custom_resource_search.py
> +            and settings.CUSTOM_SEARCH_CLASSES
```suggestion
            if settings.setting_exists("CUSTOM_MAPPING_HOOKS")
            and settings.CUSTOM_MAPPING_HOOKS
```

2024-09-11 01:43 UTC, whatisgalen commented on arches/app/search/mappings.py
> +    for custom_search_class in CustomResourceSearchFactory.get_custom_search_classes():
```suggestion
    for custom_mapping_hook in CustomMappingHookFactory.get_custom_mapping_hook_classes():
```

2024-09-11 01:43 UTC, whatisgalen commented on arches/app/search/custom_resource_search.py
> +    def get_custom_search_classes():
```suggestion
    def get_custom_mapping_hook_classes():
```

2024-09-11 01:43 UTC, whatisgalen commented on arches/app/models/resource.py
> +from arches.app.search.custom_resource_search import CustomResourceSearchFactory
```suggestion
from arches.app.search.custom_mapping_hook import CustomMappingHookFactory
```

2024-09-11 01:43 UTC, whatisgalen commented on arches/app/models/resource.py
> +            custom_search_class.add_search_terms(self, document, terms)
```suggestion
        for (
            custom_mapping_hook_class
        ) in CustomMappingHookFactory. get_custom_mapping_hook_classes():
            custom_mapping_hook_class.add_search_terms(self, document, terms)
```

2024-09-11 01:43 UTC, whatisgalen commented on arches/app/search/mappings.py
> +        ] = custom_search_class.get_custom_search_config()
```suggestion
            custom_mapping_hook.get_custom_mapping_property()
        ] = custom_mapping_hook.get_custom_mapping()
```

2024-09-11 01:43 UTC, whatisgalen commented on arches/install/arches-templates/project_name/settings.py-tpl
> +# CUSTOM_SEARCH_CLASSES = ["{{ project_name }}.search.custom_resource_search.CustomResourceSearch"]
```suggestion
# CUSTOM_MAPPING_HOOKS = ["{{ project_name }}.search.custom_mapping_hook.CustomMappingHook"]
```

2024-09-11 01:43 UTC, whatisgalen commented on tests/test_settings.py
> +CUSTOM_SEARCH_CLASSES = ["tests.views.search_tests.TestCustomResourceSearch"]
```suggestion
CUSTOM_MAPPING_HOOKS = ["tests.views.search_tests.TestCustomResourceSearch"]
```

2024-09-11 01:43 UTC, whatisgalen commented on tests/views/search_tests.py
> +from arches.app.search.custom_resource_search import CustomResourceSearch
```suggestion
from arches.app.search.custom_mapping_hook import CustomMappingHook
```

2024-09-11 01:43 UTC, whatisgalen commented on tests/views/search_tests.py
> +class TestCustomResourceSearch(CustomResourceSearch):
```suggestion
class TestCustomResourceSearch(CustomMappingHook):
```

2024-09-11 01:43 UTC, whatisgalen commented on tests/views/search_tests.py
> +        document[CustomResourceSearch.get_custom_search_path()].append(
```suggestion
        if CustomMappingHook.get_custom_mapping_property() not in document:
            document[CustomMappingHook.get_custom_mapping_property()] = []
        document[CustomMappingHook.get_custom_mapping_property()].append(
```

2024-09-11 01:43 UTC, whatisgalen commented on tests/views/search_tests.py
> +        document_key = CustomResourceSearch.get_custom_search_path()
```suggestion
        document_key = CustomMappingHook.get_custom_mapping_property()
```

2024-09-11 17:19 UTC, apeters commented
I agree with all those suggestions @whatisgalen

2024-09-19 15:13 UTC, chiatt approved these changes
Just tested this again with it's recent changes and it's working as expected.

2024-09-19 17:39 UTC, whatisgalen requested changes

2024-09-19 17:39 UTC, whatisgalen commented on arches/app/search/es_mapping_modifier.py
> +    def get_custom_search_config():
```suggestion
    def get_mapping_definition():
```

see this [doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html) on the mapping definition

2024-09-19 17:39 UTC, whatisgalen commented on arches/app/search/es_mapping_modifier.py
> +    def get_custom_search_path():
```suggestion
    def get_mapping_property():
```

see this [doc example](https://www.elastic.co/guide/en/elasticsearch/reference/current/explicit-mapping.html) of the es mapping property

2024-09-19 18:01 UTC, whatisgalen approved these changes
looks good!

2024-09-19 18:46 UTC, merged