[WIP] Isolate controlled lists into separate django app
archesproject/arches pull request #11072
Opened 2024-06-20 21:25 UTC by jacobtylerwalls

### Description of Change
These models and views were siloed enough that it raises the question of whether they should be isolated in the django app registry as well to facilitate independent migrations, etc.

### TODO:
- [ ] Remove reference datatype from core (probably a bug here with arches applications)
- [ ] Rename models/tables to remove redundant word "Controlled" now that the app name contains that word
- [ ] Functional tests (have only run the unit tests so far, haven't built webpack)
- [ ] Nuke run_tests.py, or spin up a new ticket for reorganizing the test runner entrypoint

2024-06-26 20:19 UTC, jacobtylerwalls commented on tests/run_tests.py
> -    run_all(sys.argv)
This didn't seem to work as is, and couldn't verify it worked with the new controlledlists tests. We're moving to pyproject.toml, so we may be removing this as soon as 7.6 anyway.

2024-06-28 21:40 UTC, jacobtylerwalls commented
@johnatawnclementawn Heads up, the table names changed in the latest, so the `__arches_migrate_collections_to_clm` function needs an update when you have a chance. Thanks.

2024-07-11 23:02 UTC, chrabyrd requested changes
Haven't gone too deeply yet but there's a few off-the-cuff things to start:

- can `controlledlists` be delineated?

- can `controlledlists` have its own `src` dir? My thinking is that it should be as seperate from arches as possible. Happy to jump in and hammer out the webpack update for this branch when ready 👍

2024-07-17 18:06 UTC, chrabyrd commented
This should be superseded by the work in https://github.com/archesproject/arches/issues/11201

2024-07-17 18:21 UTC, closed without merging

2024-07-18 20:30 UTC, jacobtylerwalls commented
Some notes @johnatawnclementawn:
- I pushed a few more commits but you can't see them from the closed PR view, so make sure you use the [branch comparison](https://github.com/archesproject/arches/compare/dev/8.0.x...jtw/isolate-controlled-lists)
- After creating the project, I would (if it were me) work commit by commit, doing a `git checkout <hash>` in arches and copying files over, adjusting names as needed, etc (this will help me as a reviewer)
- Some can be ignored, e.g. the first commit on this branch, as well as the very recent ones adding aliases to the core arches webpack config
- looks like I hadn't yet moved the translations out of javascript.htm, so I would look at the javascript.htm changes in the [reversion PR](https://github.com/archesproject/arches/pull/11209/files#diff-076035587e211aef326ed1561044587af7b83c04a532da48cc0acef16b464528) and make sure those port over