Fix ResourceWarnings from unclosed files #11091
archesproject/arches pull request #11108
Opened 2024-06-30 21:13 UTC by HarisMughal

### Types of changes

-   [X] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

Replace `open` calls with `open(...)`  to avoid `ResourceWarning`

### Issues Solved

Closes #11091

### Checklist

-   I targeted one of these branches:
    - [X] dev/7.6.x (under development): features, bugfixes not covered below
    - [ ] dev/7.5.x (main support): regressions, crashing bugs, security issues, major bugs in new features
    - [ ] dev/6.2.x (extended support): major security issues, data loss issues
-   [ ] I added a changelog in arches/releases
-   [ ] I submitted a PR to arches-docs (if appropriate)
-   [ ] Unit tests pass locally with my changes
-   [ ] I added tests that prove my fix is effective or that my feature works
-   [ ] My test fails on the target branch

#### Ticket Background
*   Sponsored by: 
*   Found by: @jacobtylerwalls 
*   Tested by: @HarisMughal 
*   Designed by: @ 

### Further comments

2024-06-30 21:15 UTC, HarisMughal commented
Apologies for any mistakes, this is my first contribution.
Let me know if I need to change anything

2024-07-01 14:35 UTC, jacobtylerwalls requested changes
Thanks for this contribution! I pushed minor formatting edits.

(For your next contribution, you can install the dev requirements under /install/requirements_dev.txt and then run `pre-commit install` to get the formatting hook to run on commit.)

Then, that exposed a few failing unit tests. Once fixed, this should be mergeable. Thanks again.

2024-07-01 14:35 UTC, jacobtylerwalls commented on tests/exporter/resource_export_tests.py
> +            self.assertDictEqual(dict(csv_input), dict(csv_output))
OK to leave this unindented

2024-07-01 14:35 UTC, jacobtylerwalls commented on arches/app/utils/data_management/resources/importer.py
>                          self.business_data = list(data)
This also needs indenting, see test failure

2024-07-01 14:35 UTC, jacobtylerwalls commented on arches/management/commands/packages.py
> +                    configs = json.load()
```suggestion
                    configs = json.load(f)
```

2024-07-01 15:33 UTC, jacobtylerwalls approved these changes
Thanks for the contribution!

2024-07-01 15:36 UTC, merged

2024-07-01 15:53 UTC, HarisMughal commented
IDK why autopep8 did not work on my VScode so I had to manually run it. I ran all lib install in req_dev.txt but was unaware of hooks. I will be careful next time

Thank you for letting me contribute! @jacobtylerwalls