Fixes bug stopping Url datatype widget input boxes updating when adding and editing in multi-card workflow step
archesproject/arches pull request #11138
Opened 2024-07-05 14:50 UTC by aj-he

- also handles preview when url is falsey

### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

When a UrlDatatype widget is part of a multi-card step of a workflow, the `url` and `url_label` input boxes don't clear when adding and editing the data.

This lead to confusion when trying to create an edit data in the workflows.

### Issues Solved

Closes #11136 

### Checklist

-   I targeted one of these branches:
    - [ ] dev/7.6.x (under development): features, bugfixes not covered below
    - [x] dev/7.5.x (main support): regressions, crashing bugs, security issues, major bugs in new features
    - [ ] dev/6.2.x (extended support): major security issues, data loss issues
-   [x] I added a changelog in arches/releases
-   [ ] I submitted a PR to arches-docs (if appropriate)
-   [ ] Unit tests pass locally with my changes
-   [ ] I added tests that prove my fix is effective or that my feature works
-   [ ] My test fails on the target branch

#### Accessibility Checklist

[Developer Guide](https://arches.readthedocs.io/en/stable/developing/advanced/accessibility/)

| Topic            | Changed | Retested |
| ---------------- | ------- | -------- |
| Color contrast   |         |          |
| Form fields      |         |          |
| Headings         |         |          |
| Links            |         |          |
| Keyboard         |         |          |
| Responsive Design|         |          |
| HTML validation  |         |          |
| Screen reader    |         |          |

#### Ticket Background
*   Sponsored by: Historic England
*   Found by: @csmith-he @aj-he 
*   Tested by: @csmith-he 
*   Designed by: @aj-he

### Further comments

2024-07-05 14:52 UTC, aj-he commented
tracking PR in AfHER: https://github.com/archesproject/arches-her/issues/1218

2024-07-08 21:17 UTC, chiatt requested changes

2024-07-08 21:17 UTC, chiatt commented on releases/7.5.3.md
> +- Fixes bug stopping Url datatype widget input boxes updating when adding and editing in multi-card workflow step #11136
It's good to avoid adding new lines to the end of the list just to avoid merge conflicts.

2024-07-10 00:05 UTC, chiatt approved these changes
LGTM!

2024-07-10 16:25 UTC, merged