Fix logic that sets edit link visibility #11213
archesproject/arches pull request #11214
Opened 2024-07-19 15:34 UTC by chiatt

### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change
Displays edit link in search results if user has edit permissions on an instance.

### Issues Solved

Closes #11213

### Checklist

-   I targeted one of these branches:
    - [x] dev/7.6.x (under development): features, bugfixes not covered below
    - [ ] dev/7.5.x (main support): regressions, crashing bugs, security issues, major bugs in new features
    - [ ] dev/6.2.x (extended support): major security issues, data loss issues
-   [ ] I added a changelog in arches/releases
-   [ ] I submitted a PR to arches-docs (if appropriate)
-   [ ] Unit tests pass locally with my changes
-   [ ] I added tests that prove my fix is effective or that my feature works
-   [ ] My test fails on the target branch

#### Accessibility Checklist

[Developer Guide](https://arches.readthedocs.io/en/stable/developing/advanced/accessibility/)

| Topic            | Changed | Retested |
| ---------------- | ------- | -------- |
| Color contrast   |         |          |
| Form fields      |         |          |
| Headings         |         |          |
| Links            |         |          |
| Keyboard         |         |          |
| Responsive Design|         |          |
| HTML validation  |         |          |
| Screen reader    |         |          |

#### Ticket Background
*   Sponsored by: 
*   Found by: @ 
*   Tested by: @ 
*   Designed by: @ 

### Further comments

2024-07-19 16:48 UTC, aarongundel approved these changes
Makes sense.

2024-07-19 16:49 UTC, aarongundel requested changes
Looks like there's a black formatting issue detected here.  Other than that, this makes sense.

2024-07-22 18:19 UTC, chrabyrd commented
This is blocking some resource instance lifecycle work, so I'm adding myself as reviewer/assignee after a chat with Aaron 👍

2024-07-22 18:32 UTC, chrabyrd approved these changes
lgtm 👍

2024-07-22 18:32 UTC, chrabyrd commented on arches/app/views/search.py
> +    dsl.include("permissions")
`permissions` was not available in the `get_search_ui_permissions` method

2024-07-22 19:02 UTC, chrabyrd commented on arches/app/permissions/arches_standard.py
> -        if self.user_is_resource_editor(user):
after a chat w/Cyrus I understand this is the intended behavior.

2024-07-22 19:25 UTC, merged