return dsl unserialized, re #11386
archesproject/arches pull request #11387
Opened 2024-08-22 18:14 UTC by whatisgalen

### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

### Issues Solved

Closes #

### Checklist

-   I targeted one of these branches:
    - [ ] dev/7.6.x (under development): features, bugfixes not covered below
    - [ ] dev/7.5.x (main support): regressions, crashing bugs, security issues, major bugs in new features
    - [ ] dev/6.2.x (extended support): major security issues, data loss issues
-   [ ] I added a changelog in arches/releases
-   [ ] I submitted a PR to arches-docs (if appropriate)
-   [ ] Unit tests pass locally with my changes
-   [ ] I added tests that prove my fix is effective or that my feature works
-   [ ] My test fails on the target branch

#### Accessibility Checklist

[Developer Guide](https://arches.readthedocs.io/en/stable/developing/advanced/accessibility/)

| Topic            | Changed | Retested |
| ---------------- | ------- | -------- |
| Color contrast   |         |          |
| Form fields      |         |          |
| Headings         |         |          |
| Links            |         |          |
| Keyboard         |         |          |
| Responsive Design|         |          |
| HTML validation  |         |          |
| Screen reader    |         |          |

#### Ticket Background
*   Sponsored by: 
*   Found by: @ 
*   Tested by: @ 
*   Designed by: @ 

### Further comments

2024-08-22 20:24 UTC, apeters requested changes
I would suggest that in `base_search_view.py` that when the method `handle_search_results_query` is called that it returns a consistent object.  So, for example, when using `returnDsl=True` that the return object looks like this:
```
(None, search_query_object)
```
None being the search result, as there is not search result when requesting the dsl.

2024-08-22 20:24 UTC, apeters commented on arches/app/views/search.py
> +            return response_object
```suggestion
        if returnDsl:
            return search_query_object.pop("query", None)
```

2024-08-22 20:37 UTC, whatisgalen commented on arches/app/views/search.py
> +            return response_object
change in latest

2024-08-23 04:17 UTC, njkim approved these changes
Looks good, thanks.

2024-08-23 04:18 UTC, merged