Allow number datatype node values to be searchable
archesproject/arches pull request #11623
Opened 2024-11-13 18:56 UTC by SDScandrettKint

### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

Numbers currently aren't indexed as terms.  This PR adds `get_search_terms` to the number datatype

### Issues Solved

Closes #11619 

### Checklist

-   I targeted one of these branches:
    - [x] dev/8.0.x (under development): features, bugfixes not covered below
    - [ ] dev/7.6.x (main support): regressions, crashing bugs, security issues, major bugs in new features
    - [ ] dev/6.2.x (extended support): major security issues, data loss issues
-   [ ] I added a changelog in arches/releases
-   [ ] I submitted a PR to arches-docs (if appropriate)
-   [ ] Unit tests pass locally with my changes
-   [ ] I added tests that prove my fix is effective or that my feature works
-   [ ] My test fails on the target branch

#### Accessibility Checklist

[Developer Guide](https://arches.readthedocs.io/en/stable/developing/advanced/accessibility/)

| Topic            | Changed | Retested |
| ---------------- | ------- | -------- |
| Color contrast   |         |          |
| Form fields      |         |          |
| Headings         |         |          |
| Links            |         |          |
| Keyboard         |         |          |
| Responsive Design|         |          |
| HTML validation  |         |          |
| Screen reader    |         |          |

#### Ticket Background
*   Sponsored by: Knowledge Integration
*   Found by: @SDScandrettKint  
*   Tested by: @SDScandrettKint  
*   Designed by: @SDScandrettKint  

### Further comments

2024-11-13 19:02 UTC, SDScandrettKint commented
Note that whilst the number now appears in the terms index, it is still not searchable, as the resource isn't correctly matched

https://github.com/user-attachments/assets/e4ad3a81-7483-47ec-95db-b81300dd6cf5



This is because the resources index search query is looking by default at the strings array, when it needs to be looking at numbers.  
Below is the search query that is trying to be used, but resulting in no match.
```
    "query": {
        "bool": {
            "filter": [
                {
                    "terms": {
                        "graph_id": [
                            "ff623370-fa12-11e6-b98b-6c4008b05c4c",
                            "9797cab0-a1cc-11ef-bab9-00155dcc32ab",
                            "85ae1a72-a1ac-11ef-baca-00155dcc32ab",
                            "eec18762-ba59-4fde-9a5f-732bf02a020d"
                        ]
                    }
                }
            ],
            "must": [
                {
                    "nested": {
                        "path": "numbers",
                        "query": {
                            "bool": {
                                "filter": [
                                    {
                                        "terms": {
                                            "strings.nodegroup_id": [
                                                "85ae2a80-a1ac-11ef-baca-00155dcc32ab",
                                                "85ae2c7e-a1ac-11ef-baca-00155dcc32ab",
                                                "20000000-0000-0000-0000-100000000000",
                                                "32f2d663-fae4-11e6-83ad-6c4008b05c4c",
                                                "9797d4ba-a1cc-11ef-bab9-00155dcc32ab",
                                                "9797cc54-a1cc-11ef-bab9-00155dcc32ab",
                                                "186dd1d0-a1cc-11ef-af55-00155dcc32ab",
                                                "1832f5f6-a1cc-11ef-af55-00155dcc32ab",
                                                "c5a2a914-fadd-11e6-8f8f-6c4008b05c4c",
                                                "c5a2a2e8-fadd-11e6-9849-6c4008b05c4c",
                                                "c5a2b1dc-fadd-11e6-a726-6c4008b05c4c",
                                                "c5a2b530-fadd-11e6-b5f6-6c4008b05c4c",
                                                "d0987880-fad8-11e6-8cce-6c4008b05c4c",
                                                "47f77992-a1cc-11ef-af55-00155dcc32ab",
                                                "47f78040-a1cc-11ef-af55-00155dcc32ab",
                                                "47f77cd0-a1cc-11ef-af55-00155dcc32ab",
                                                "47f77eb0-a1cc-11ef-af55-00155dcc32ab",
                                                "58ef6f34-a1b8-11ef-b268-00155dcc32ab",
                                                "feb95991-fa14-11e6-974f-6c4008b05c4c",
                                                "5fa8acfa-a1b8-11ef-b268-00155dcc32ab",
                                                "67b8049a-a1b8-11ef-b268-00155dcc32ab",
                                                "67b80742-a1b8-11ef-b268-00155dcc32ab",
                                                "85ae2e90-a1ac-11ef-baca-00155dcc32ab",
                                                "85ae308e-a1ac-11ef-baca-00155dcc32ab",
                                                "85ae3296-a1ac-11ef-baca-00155dcc32ab",
                                                "85ae265c-a1ac-11ef-baca-00155dcc32ab",
                                                "85ae34ee-a1ac-11ef-baca-00155dcc32ab",
                                                "85ae1c5c-a1ac-11ef-baca-00155dcc32ab",
                                                "85ae2242-a1ac-11ef-baca-00155dcc32ab",
                                                "85ae2012-a1ac-11ef-baca-00155dcc32ab",
                                                "85ae2468-a1ac-11ef-baca-00155dcc32ab",
                                                "85ae2864-a1ac-11ef-baca-00155dcc32ab",
                                                "92791872-a1cc-11ef-bf20-00155dcc32ab",
                                                "9279161a-a1cc-11ef-bf20-00155dcc32ab",
                                                "9797d280-a1cc-11ef-bab9-00155dcc32ab",
                                                "9797d00a-a1cc-11ef-bab9-00155dcc32ab",
                                                "0e8fdef0-4148-11e7-8330-c4b301baab9f",
                                                "0e8fe457-4148-11e7-9c10-c4b301baab9f",
                                                "0e8ff675-4148-11e7-9c88-c4b301baab9f",
                                                "0e8fe87a-4148-11e7-aa8b-c4b301baab9f",
                                                "0e8ff31c-4148-11e7-998a-c4b301baab9f"
                                            ]
                                        }
                                    }
                                ],
                                "must": [
                                    {
                                        "match_phrase": {
                                            "strings.string": {
                                                "query": "54"
                                            }
                                        }
                                    },
                                    {
                                        "match": {
                                            "strings.nodegroup_id": {
                                                "query": "5fa8acfa-a1b8-11ef-b268-00155dcc32ab"
                                            }
                                        }
                                    }
                                ],
                                "must_not": [],
                                "should": []
                            }
                        }
                    }
                }
            ],
            "must_not": [],
            "should": []
        }
    },
```

The datatype of a search term is not currently stored (or known), so unless we use that, or check whether a term is an integer and then run both the string search and number search (as numbers could be stored in a string node).

2024-11-14 01:25 UTC, chiatt requested changes
This looks good to me. I think it just needs an entry in the changelog.

2024-11-14 16:54 UTC, chiatt approved these changes

2024-11-14 18:32 UTC, apeters approved these changes
looks good!

2024-11-14 21:34 UTC, merged