Mark passwords as sensitive variables #11652
archesproject/arches pull request #11653
Opened 2024-11-25 14:54 UTC by jacobtylerwalls

### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change
Limit occurrences of passwords in error reports (if configured) in production.

### Issues Solved

Closes #11652

2024-11-25 19:30 UTC, jacobtylerwalls commented
You can test with the standard django error view but, since DEBUG=True doesn't bother masking, the least realistic but fatest way to configure this to test would be hack this line in your django install to return True:

https://github.com/django/django/blob/857b1048d53ebf5fc5581c110e85c212b81ca83a/django/views/debug.py#L182

Then you should be able to throw errors inside any of these views and see the masking inside the django error view (but again, more realistically, we'd be talking about logs or emails to admins in prod environments, not the django error view):


<img width="550" alt="Screenshot 2024-11-25 at 2 11 17 PM" src="https://github.com/user-attachments/assets/d1065d84-bec2-47ec-b020-b860f89aa76b">

2025-01-18 01:29 UTC, chiatt requested changes
This is really great. Could you make the variables sensitive on the post method in the SignupView in `views/auth.py` as well?

2025-01-23 17:40 UTC, chiatt requested changes

2025-01-23 17:40 UTC, chiatt commented on arches/app/views/auth.py
> +    )
This only seems to work when the methods are within an iterator (as I see you've done elsewhere)

2025-01-23 21:07 UTC, chiatt approved these changes

2025-01-23 21:07 UTC, merged