Moves node.name validation logic to graph.validate, re #6765
archesproject/arches pull request #6766
Opened 2020-10-21 15:04 UTC by chiatt

Moves node.name validation logic to graph.validate to prevent error when appending new nodes to a graph, re #6765

2020-10-21 20:18 UTC, apeters approved these changes
checked all pathways in the code and everything looks solid.  Tried importing a graph with duplicate names as well and that fails to load as expected.

2020-10-21 22:13 UTC, apeters requested changes
see below

2020-10-21 22:26 UTC, apeters requested changes
There are 2 issues I found:
1. You can append the same branch several times without issue (violates sibling node constraint)
2. If you have 2 nodes that are parent and child.  They have the same name but the child node is in it's own card.  Then you change the child node to not be in it's own card.  The UI then hangs.

2020-10-23 12:44 UTC, chiatt commented
Closing because the commits in this PR are now also in #6779 which addresses the comments in @apeters review.

2020-10-23 12:44 UTC, closed without merging