fix bug where undo is incorrectly displayed, re #7526
archesproject/arches pull request #7527
Opened 2021-06-22 01:39 UTC by apeters

re #7526

2021-06-22 21:19 UTC, chrabyrd requested changes
These changes do not allow a step that hasn't been saved yet to clear properly.

see https://recordit.co/Ddw1ZZSk4X

2021-06-22 22:53 UTC, apeters commented
I think this is a workflow config issue.  If you add the param: `'renderContext': 'workflow'` then this should work

2021-06-24 02:18 UTC, chrabyrd commented
> I think this is a workflow config issue. If you add the param: `'renderContext': 'workflow'` then this should work

Yep! That was it, merging now

2021-06-24 02:18 UTC, chrabyrd approved these changes

2021-06-24 02:19 UTC, merged