7541 add include ink report option
archesproject/arches pull request #7586
Opened 2021-07-12 11:12 UTC by csmith-he

Fulfils requirement for ticket #7541 .  Tested successfully in Historic England keystone installations.

Making the new UI element accessible will take place as part of the wider Accessibility work as the whole export panel needs to be looked at for accessibility.

2021-07-12 11:34 UTC, csmith-he commented
@chiatt Here's the PR for the #7541

2021-07-19 19:21 UTC, chiatt requested changes

2021-07-20 10:36 UTC, csmith-he commented on arches/app/search/search_export.py
> +                    resource["Link"] = str(settings.ARCHES_NAMESPACE_FOR_DATA_EXPORT).rstrip("/") + "/report/" + str(resource["resourceid"])
Cheers, @chiatt!  That should all be sorted now.

2021-07-20 17:53 UTC, chiatt commented on arches/app/search/search_export.py
> +                    resource["Link"] = str(settings.ARCHES_NAMESPACE_FOR_DATA_EXPORT).rstrip("/") + "/report/" + str(resource["resourceid"])
Excellent - thanks @csmith-he!

2021-07-20 17:53 UTC, chiatt approved these changes

2021-07-20 17:53 UTC, merged