update disambiguated json output, version label based graph
archesproject/arches pull request #7589
Opened 2021-07-12 20:01 UTC by apeters

re #7314

2021-07-13 22:07 UTC, chrabyrd reviewed
overall looks good! Only thing I really have is that the tests from v1 should make it over to v2

2021-07-13 22:07 UTC, chrabyrd commented on arches/app/utils/label_based_graph_v2.py
> +from arches.app.datatypes.datatypes import DataTypeFactory
The only difference between this and V1 is the changing the `get_display_value` call to `to_json`, yeah? Should we be duplicating everything, or should we work versioning logic into the current endpoint? Or maybe follow an inheritance pattern and overwrite the one method?

2021-07-14 22:13 UTC, chiatt reviewed
I reviewed the output of each datatype and they all make sense to me. The one exception maybe, as we discussed earlier, is the 'selected' property on the domain and domain list datatypes. It seems unnecessary, but I'm not sure if it should be filtered out here or whether it ought to be removed from the config itself.

2021-07-15 01:01 UTC, chiatt approved these changes

2021-07-15 15:50 UTC, chrabyrd requested changes
just wanna make sure we don't accidentally merge before getting the v1 tests in ;-)

2021-07-22 18:27 UTC, apeters commented
Here's a model of all datatypes to test with.

[_All Datatypes.json.txt](https://github.com/archesproject/arches/files/6864502/_All.Datatypes.json.txt)

2021-07-23 18:28 UTC, apeters commented
@chiatt, @chrabyrd, because the timeing is critical, maybe we should write a ticket specifically for crating tests for the v2 version of label_based_graph, so we can merge this in sooner rather than later.

2021-07-23 23:12 UTC, chrabyrd approved these changes
@apeters agreed! It might also be a good exercise to get peoples' feet wet with testing patterns.

2021-07-24 02:29 UTC, chiatt commented
@apeters & @chrabyrd I just noticed your latest comments. This afternoon I added a new file for the v2 tests in this PR: https://github.com/archesproject/arches/pull/7636

2021-07-24 02:29 UTC, merged