7830 usability adv search facet click area
archesproject/arches pull request #8175
Opened 2022-02-23 17:35 UTC by phudson-he

### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change
Advanced Search - make whole area of the facet header clickable. As per issue raised... #7830 

### Issues Solved
Entire facet header now clickable instead of just the expand/collapse icon.
#

### Checklist

-   [x] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: Historic England
*   Found by: @rlwilliamss
*   Tested by: @rlwilliamss
*   Designed by: @phudson-he

### Further comments

2022-02-23 23:16 UTC, aarongundel requested changes
You may want to put these items up a level higher in the DOM - the cursor on the search-facet-item itself and the click there as well.  Otherwise there's an unclickable area in the padding, which seems like it should be clickable.

2022-03-01 09:57 UTC, phudson-he commented
@aarongundel As suggested, latest commit moves the clickable element higher in the DOM

2022-03-07 17:42 UTC, aarongundel commented
looks good!

2022-03-07 17:43 UTC, aarongundel approved these changes

2022-03-07 17:43 UTC, merged