Fixed the error explained in issue #8310, that is:
archesproject/arches pull request #8315
Opened 2022-03-31 09:29 UTC by jakub-gorka

exporting mapping files doesn't work as expected in command line. This changes enables export of single resource models in command line utility. fixed:
IsADirectoryError: [Errno 21] Is a directory: '<output_dir>'
TypeError: string argument expected, got 'bytes'

### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

Added temporary name to config file, that is a temporary workaround
Changed usage of StringIO to BytesIO in zip saving

### Issues Solved

#8310 

### Checklist

-   [ ] Unit tests pass locally with my changes (i get No module named 'tests.test_settings' error)
-   [x] I have added tests that prove my fix is effective or that my feature works (downloaded mapping files from my project)
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: Warsaw University of Technology
*   Found by: @jakub-gorka
*   Tested by: @jakub-gorka
*   Designed by: @jakub-gorka

### Further comments

More changes are needed for this exporter script to work as described in readthedocs. first change should be at the beggining of 'def create_mapping_configuration_file', where 'graphid = uuid.UUID(graphid)' doesn't really do anything but throws an error with invalid UUID. Only then checks for multiple UUIDs or keywords (like 'all') can be made.

2022-03-31 09:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/archesproject/arches?pullRequest=8315) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/archesproject/arches?pullRequest=8315) before we can accept your contribution.<br/><hr/>**Jacob** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/archesproject/arches?pullRequest=8315) it.</sub>

2022-04-01 16:36 UTC, chiatt requested changes
Thanks @jakub-gorka, I tested this and it worked like a charm. The only change that would be nice to see is removal of the lines that write the config file (261-262). That file no longer appears needed. Also, please be sure sign the CLA so we can merge in your code. Thanks!

2022-04-01 16:36 UTC, chiatt commented on arches/app/utils/data_management/resource_graphs/exporter.py
>              json.dump(export_json, config_file, indent=4)
I can see why you made the change on 261, but it looks like writing out the config file is actually no longer needed. Could you remove lines 261 and 262.

2022-04-11 11:47 UTC, jakub-gorka commented
Hi, i accepted the CLA, please re-review my pull request

2022-04-12 15:10 UTC, jakub-gorka commented
Removed those lines,  can you please merge it?

2022-04-13 15:38 UTC, chiatt approved these changes

2022-04-13 15:58 UTC, merged

2022-04-13 15:58 UTC, chiatt commented
Although Github check currently shows the CLA as unsigned, jakup-gorka is on the signature list having signed on Apr 4, 2022.

Thanks very much for resolving this issue @jakub-gorka