8424 hard coded permissions url
archesproject/arches pull request #8425
Opened 2022-05-12 17:28 UTC by bferguso

### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

Add context root to clear-user-permission-cache URLs

### Issues Solved

#8424

### Checklist

-   [ ] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: Self Funded
*   Found by: @bferguso
*   Tested by: @bferguso
*   Designed by: @bferguso

### Further comments

2022-05-12 17:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/archesproject/arches?pullRequest=8425) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/archesproject/arches?pullRequest=8425) before we can accept your contribution.<br/>**7** out of **9** committers have signed the CLA.<br/><br/>:white_check_mark: njkim<br/>:white_check_mark: chiatt<br/>:white_check_mark: apeters<br/>:white_check_mark: bferguso<br/>:white_check_mark: robgaston<br/>:white_check_mark: aarongundel<br/>:white_check_mark: chrabyrd<br/>:x: dependabot[bot]<br/>:x: dependabot-preview[bot]<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/archesproject/arches?pullRequest=8425) it.</sub>

2022-05-16 23:36 UTC, apeters requested changes
@bferguso, I think the way to do this properly is to use django's `reverse` url functionality (see [https://docs.djangoproject.com/en/4.0/ref/urlresolvers/#reverse](https://docs.djangoproject.com/en/4.0/ref/urlresolvers/#reverse)).
You can use that directly from within the .html template like so
```request.open("POST", "{% url 'clear_user_permission_cache' %}", true);```

To use that in the .js file you'll need to create a new entry in `javascript.htm` under the `arches.urls` section (lines ~170-280).  See the entries there for examples of how to do that.  Then use that new value directly in `persmission-settings-form.js` like you used `arches.urls.root`.

2022-05-19 12:42 UTC, bferguso commented
> @bferguso, I think the way to do this properly is to use django's `reverse` url functionality (see https://docs.djangoproject.com/en/4.0/ref/urlresolvers/#reverse). You can use that directly from within the .html template like so `request.open("POST", "{% url 'clear_user_permission_cache' %}", true);`
> 
> To use that in the .js file you'll need to create a new entry in `javascript.htm` under the `arches.urls` section (lines ~170-280). See the entries there for examples of how to do that. Then use that new value directly in `persmission-settings-form.js` like you used `arches.urls.root`.

@apeters  - That's a much better solution - thanks for pointing me in the right direction.

2022-05-19 18:55 UTC, apeters approved these changes
works as expected

2022-05-19 18:56 UTC, merged