Prevent excess tiles cardinality-1 when tile saved using db function, #8459
archesproject/arches pull request #8460
Opened 2022-05-23 05:12 UTC by njkim

### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

Fix the issue creating multiple tiles for cardinality 1 card when using db function to save the tiles. #8459
Also, add the trigger to check multiple tiles for cardinality 1 card.

### Issues Solved

#8459 

### Checklist

-   [ ] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: 
*   Found by: @ 
*   Tested by: @ 
*   Designed by: @ 

### Further comments

2022-05-27 18:57 UTC, njkim commented on arches/app/models/tile.py
> -        if settings.BYPASS_CARDINALITY_TILE_VALIDATION:
Good findings, thanks.

2022-05-31 23:35 UTC, chiatt approved these changes

2022-06-01 00:06 UTC, chiatt requested changes
Works as expected

2022-06-01 00:06 UTC, chiatt commented on arches/app/models/migrations/8009_etlmodule.py
> +                UNION
The SELECT statement on line 147 doesn't have the join to the nodegroups table, so they aren't filtered by cardinality. I think the following update would ensure cardinality n nodegroups aren't included:
```
	SELECT resourceid, ng1.nodegroupid, COALESCE(parenttileid::text, '')
		FROM load_staging ls, node_groups ng1
		WHERE ls.nodegroupid = ng1.nodegroupid
		AND ng1.cardinality = '1'
		GROUP BY resourceid, ng1.nodegroupid, COALESCE(parenttileid::text, ''), loadid
		HAVING count(*) > 1
		AND loadid = ls.loadid
```

2022-06-01 16:39 UTC, chiatt approved these changes

2022-06-01 18:30 UTC, merged