8400 cbyrd remove references to arches collector
archesproject/arches pull request #8599
Opened 2022-06-23 20:09 UTC by chrabyrd

### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

Removes all references to Arches collector

### Issues Solved

#8400 

### Further comments

2022-07-02 00:44 UTC, chiatt requested changes
Hey @chrabyrd - This looks really good. There are just a few are just a few minor changes that I think would be worth making.

2022-07-02 00:44 UTC, chiatt commented on tests/views/api_tests.py
> -    def test_api_base_view(self):
I think the mobilesurvey endpoint could just be swapped out for another endpoint.  The test passed for me using `api_node_value`.


```
    def test_api_base_view(self):
        """
        Test that our custom header parameters get pushed on to the GET QueryDict

        """
        factory = RequestFactory(HTTP_X_ARCHES_VER="2.1")
        view = APIBase.as_view()

        request = factory.get(reverse("api_node_value", kwargs={}), {"ver": "2.0"})
        request.user = None
        response = view(request)
        self.assertEqual(request.GET.get("ver"), "2.0")

        request = factory.get(reverse("api_node_value"), kwargs={})
        request.user = None
        response = view(request)
        self.assertEqual(request.GET.get("ver"), "2.1")
        ```

2022-07-02 00:44 UTC, chiatt commented on tests/fixtures/testing_prj/testing_prj/settings.py
> +OAUTH_CLIENT_ID = ""  # '9JCibwrWQ4hwuGn5fu2u1oRZSs9V6gK8Vu8hpRC4'
The release notes should mention that this setting has been changed. Admins will have to modify it in their projects.

2022-07-02 00:44 UTC, chiatt commented on arches/app/media/css/arches.scss
>  .mpm-project-card {
`.mpm` was an abbreviation for 'mobile-project-manager', so those classes can probably be removed as well (hopefully they weren't used anywhere else.

2022-07-02 02:15 UTC, chrabyrd commented
@chiatt this should be g2g now

2022-07-04 15:34 UTC, chiatt approved these changes

2022-07-04 15:35 UTC, merged