8650 etl modules trans strings
archesproject/arches pull request #8655
Opened 2022-07-13 20:18 UTC by njkim

### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

### Issues Solved

#8650, #8651

### Checklist

-   [ ] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: 
*   Found by: @ 
*   Tested by: @ 
*   Designed by: @ 

### Further comments

2022-07-13 23:33 UTC, chrabyrd requested changes
overall looks good just 1 thing

2022-07-13 23:33 UTC, chrabyrd commented on arches/app/templates/javascript.htm
> +        upload-csv-zip-file='{% trans "Upload .csv or .zip File" as UploadCsvZipFile %} "{{ UploadCsvZipFile|escapejs }}"'
nit casing: `UploadCsvZipFile` -> `uploadCsvZipFile`

2022-07-13 23:56 UTC, njkim commented on arches/app/templates/javascript.htm
> +        upload-csv-zip-file='{% trans "Upload .csv or .zip File" as UploadCsvZipFile %} "{{ UploadCsvZipFile|escapejs }}"'
Good catch, thanks.

2022-07-14 17:22 UTC, chrabyrd commented
manually merged this branch

2022-07-14 17:22 UTC, closed without merging