9165 error reporting
archesproject/arches pull request #9172
Opened 2023-01-12 23:36 UTC by njkim

### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

Improve the error reporting for the bulk data manager, single-csv-importer and branch-csv-importer, #9165 

### Issues Solved

#9165

### Checklist

-   [ ] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: 
*   Found by: @ 
*   Tested by: @ 
*   Designed by: @ 

### Further comments

2023-01-25 01:22 UTC, chiatt requested changes
This looks good. There are just a few syntax formatting changes that I think would be good to make.

2023-01-25 01:22 UTC, chiatt commented on arches/app/views/etl_manager.py
> +    def dictfetchall(self, cursor):
We should probably try to avoid using Python types in function names. Maybe this could be: `fetch_load_errors(self, cursor)`

2023-01-25 01:22 UTC, chiatt commented on arches/app/models/models.py
> +class loadErrors(models.Model):
It's probably good to capitalize the class name here

2023-01-25 01:22 UTC, chiatt commented on arches/app/models/migrations/9165_error_reporting.py
> +            name="loadErrors",
change class name to 'LoadErrors'

2023-01-25 18:43 UTC, njkim commented on arches/app/models/migrations/9165_error_reporting.py
> +            name="loadErrors",
The naming issues were fixed. Thanks!

2023-03-14 00:59 UTC, chiatt approved these changes

2023-03-14 00:59 UTC, merged