9294 individualized bulk loader error reporting
archesproject/arches pull request #9303
Opened 2023-03-07 01:18 UTC by johnatawnclementawn

### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

These changes provide a default error report for the bulk data loader. In the future, this default can be overridden based on the bulk loader module's schema. 

### Issues Solved

#9294

2023-03-09 01:34 UTC, chiatt requested changes
Hey Johnathan, this looks really good, but when I click on the 'show' button in the error table, I get an error. I believe it's because the getNodeError method is missing and needs to be passed in the params. It's a method rather than an observable, so no need for the `|| ko.observable` logic. 

![image](https://user-images.githubusercontent.com/1877663/223892474-89747555-0696-47b2-b4d6-d06b2b456a5d.png)

2023-03-09 01:34 UTC, chiatt commented on arches/app/media/js/views/components/etl_modules/import-single-csv.js
> +
I believe the `getNodeError` method needs to be passed in here.

2023-03-09 15:07 UTC, johnatawnclementawn commented
Hey @chiatt, I think this should solve the issue.

2023-03-11 00:57 UTC, chiatt approved these changes

2023-03-11 00:57 UTC, merged