Upgrade bulk editor modules, #9219
archesproject/arches pull request #9334
Opened 2023-03-20 06:40 UTC by njkim

### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

### Issues Solved

#

### Checklist

-   [ ] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: 
*   Found by: @ 
*   Tested by: @ 
*   Designed by: @ 

### Further comments

2023-04-07 01:30 UTC, apeters requested changes
I think the directory structure needs to be reviewed and potentially refactored.  Let's discuss.

2023-04-07 01:30 UTC, apeters commented on arches/app/templates/views/components/etl_modules/base-editor.htm
This file should probably be renamed too.  Something corresponds to it's .js file `base-bulk-string-editor.htm`

2023-04-08 01:22 UTC, njkim commented on arches/app/etl_modules/base_data_editor.py
> +class BaseDataEditor(BaseImportModule):
The file names and class names are updated and the migration is separated and updated accordingly.
The update are going to be reflected in the pr #9383

2023-04-28 04:15 UTC, njkim commented
The branch is merged into https://github.com/archesproject/arches/pull/9383

2023-04-28 04:15 UTC, closed without merging