9498 Make search export accessible
archesproject/arches pull request #9519
Opened 2023-05-11 02:27 UTC by johnatawnclementawn

### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

Improves keyboard accessibility of search export panel

### Issues Solved

#9498

2023-05-11 02:29 UTC, johnatawnclementawn commented on arches/app/templates/views/components/search/search-export.htm
> +            <!-- <div class="search-export-instruction-h4 h4">
Moving this text to the subtitle of the switch doesn't look as nice, but it's the easiest way I thought to make it accessible.

2023-05-11 02:43 UTC, johnatawnclementawn commented on arches/app/templates/views/components/search/search-export.htm
> +            text: ('Arches is currently running without Celery. Exports will be limited to {{app_settings.SEARCH_EXPORT_IMMEDIATE_DOWNLOAD_THRESHOLD}} records. The html option is only allowed with a
Please see #9520

2023-06-22 00:48 UTC, apeters requested changes

2023-06-22 00:48 UTC, apeters commented on arches/app/templates/views/components/search/search-export.htm
> +            <div role="radiogroup" style="display: grid;" aria-labelledby="format-instruction-header">
This should probably say "Export Format" as opposed to just "Format"

2023-07-21 17:27 UTC, ryan86 approved these changes
LGTM

2023-07-21 17:27 UTC, merged