fix asterisk not showing up for required string nodes, re #9546
archesproject/arches pull request #9547
Opened 2023-05-18 19:44 UTC by apeters

re #9546
re #9281

2023-05-18 22:43 UTC, chiatt requested changes
It looks like there are a couple of typos preventing webpack from building. Also, this fixes the UI, but the node requirement is actually not enforced if you try to save a string without a value. This is because we no longer assign `None` to a string node. Instead we save the object with an empty string for each language. It's not ideal, but it allowed us to overcome dirty state issues. 

As a result this evaluation returns False and the missing value is never identified: https://github.com/archesproject/arches/blob/b32545022825912f1651fd46f32de7da26459260/arches/app/models/tile.py#L304

One solution might be to add a datatype method that reports whether a value is empty based on the nature of the data. For the string datatype, that might mean that all values in all languages are an empty string. I think this would also make sense for other datatypes that store JSON. For example, the geojson datatype might return empty if there is a geojson object that has no features.

2023-05-18 22:43 UTC, chiatt commented on arches/app/templates/views/components/widgets/rich-text.htm
> +            <span">
Looks like there is an accidental quote that ended up in this tag.

2023-05-18 22:43 UTC, chiatt commented on arches/app/templates/views/components/widgets/rich-text.htm
> +                <label class="control-label widget-input-label data-bind="text:label"></label>
A double quote is needed after `widget-input-label`

2023-05-18 22:57 UTC, chiatt approved these changes

2023-05-18 23:03 UTC, merged

2024-02-14 18:02 UTC, apeters commented
@bferguso (@chiatt ), you're right it looks like the text widget is the only one where we "lost" the asterisk (the rich-text widget seems to be ok) .  Looks like it happened somewhere between dev/7.3 and dev/7.4  This may have happened as a result of the accessibility work.
This should be fixed.  I'll make a new ticket