9661 Make base manager header accessible
archesproject/arches pull request #9681
Opened 2023-06-20 20:31 UTC by johnatawnclementawn

### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

Improves semantics & screen reader interactions with the base header navigation elements. 

### Issues Solved

#9661

2023-06-22 00:19 UTC, apeters requested changes

2023-06-22 00:19 UTC, apeters commented on arches/app/templates/base-manager.htm
> +                                        <span class="hidden-xs h5" aria-label="{% trans 'Edit your profile' %}.">{% trans "Welcome" %}, {{ user.first_name|default:user.username }}</span>
I think we might want to notify the user their logged in status as well as let then know that they can edit their profile.  Maybe it should say something like "Logged in as admin, click to edit your profile."

2023-06-22 00:19 UTC, apeters commented on arches/app/templates/base-manager.htm
> +                        <li aria-label="{% trans 'CHoose your language' %}">
This is spoken as "see hows your language".  Change to "Choose".

2023-07-21 16:49 UTC, ryan86 approved these changes
LGTM

2023-07-21 16:49 UTC, merged