9561 Json-Ld fix : Omit Edge from Null Domain
archesproject/arches pull request #9783
Opened 2023-07-17 12:05 UTC by khodgkinson-he

Issue : JSON-LD concept model handling does not handle null **domain nodes** whilst there is data in the **range node** on rdffile.py edge relationship generation.

ArchesProject GitHub Giveback Issue : #9561 

Fix : Do not parse the null. Domain node as Undefined (omitted from JSON) substitution used for Unknown (NULL value).

@chiatt @aj-he : Happy to rebase to dev/7.5.x if that'd be of help!  ^_^

2023-07-17 14:16 UTC, aj-he commented
@chiatt assigned to you for review. Delegate as you see fit.

2023-07-17 22:32 UTC, chiatt commented
Thanks @khodgkinson-he, I think dev/7.4.x is the right target for this change.

2023-07-17 22:41 UTC, chiatt requested changes
I think that we should probably inform the admin why there is data missing from the response. 
Maybe something like this?
```
if pkg["d_uri"] is None and pkg["range_tile_data"]:
    self.logger.warn(_("Unable to return range value because domain is None, re https://github.com/archesproject/arches/pull/9783/files"))
    return
```

2023-07-18 09:51 UTC, khodgkinson-he commented
@chiatt : Excellent suggestion to inform admin logs!  I've tweaked that code accordingly, sir! ^_^

2023-07-18 18:08 UTC, chiatt commented
Thanks @khodgkinson-he!

2023-07-18 18:09 UTC, chiatt approved these changes

2023-07-18 18:09 UTC, merged