Fix for allowing double quotation marks in i18n inputs (dev/7.4.x)
archesproject/arches pull request #9794
Opened 2023-07-19 15:54 UTC by SDScandrettKint

This fix allows users to have strings that start and end with double quotation marks (" ") in i18n text inputs.
### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change
Inputting a string that starts and ends with double quotation marks (e.g. "Hello, world") into any Resource Model text input box that used internationalisation would save incorrectly - e.g. as "Hello, world" rather than {"en":""\Hello, world"\"}. Strings which included double quotations not at the start and end (e.g. "Hello", world) would save correctly (e.g. {"en": ""\Hello"\, world"}. 
This change converts inputs with double quotations at the start and end to the raw literal for the character - "\ .

### Issues Solved

#9623

### Checklist

-   [x] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: Knowledge Integration
*   Found by: @SDScandrettKint 
*   Tested by: @SDScandrettKint 
*   Designed by: @SDScandrettKint 

### Further comments

2023-07-19 23:53 UTC, chiatt requested changes
This does prevent the error from occurring, but it may result in some unintended behavior. If a string has already been saved with quotes escaped, the current change will escape them a second time. When that happens you can end up with something like this: 

![image](https://github.com/archesproject/arches/assets/1877663/fb8075ca-fc05-4c91-91ae-db6ec1be4197)

I think the solution might be to check if there are quotes around the string and if those quotes are already escaped. This regex pattern might work: 
```
import re
unescaped_quotes = r'^(?<!\\)".*"(?<!\\)$'
if re.match(unescaped_quotes, value):
        value.replace('"', r'\"')
``` 
@apeters pointed out that because this is such an important part of the Arches code, we'd really need a unit test to ensure that strings are getting parsed properly.

2023-07-19 23:53 UTC, chiatt commented on arches/app/models/fields/i18n.py
> +            # fix for issue #9623 - using double quotation marks in i18n input
You can remove this line. We can always trace back to the ticket through a git blame.

2023-07-20 00:03 UTC, apeters commented
I just pushed a small fix that I think handles for the issue that @chiatt described.  I also added a test.

2023-07-20 00:32 UTC, chiatt approved these changes

2023-07-20 00:32 UTC, merged