9386 Make advanced search accessible
archesproject/arches pull request #9829
Opened 2023-07-25 01:16 UTC by johnatawnclementawn

### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

Improve advanced search accessibility

### Issues Solved

Resolves #9386 

Replaces: #9492

2023-09-22 14:47 UTC, johnatawnclementawn commented
Per conversation with Alexei, this should be revisited/reviewed after his selectwoo changes are merged into the accessibility branch

2023-10-16 21:56 UTC, apeters requested changes

2023-10-16 21:56 UTC, apeters commented on arches/app/templates/views/components/search/advanced-search.htm
> +                        aria-label="{% trans 'Filter search facets' %}"
we shouldn't be using {% trans %} tags anymore.  We should be using js tanslation objects.

2023-10-17 00:31 UTC, apeters approved these changes
looks good!

2023-10-17 00:32 UTC, merged