Update branch xls importer, #9749
archesproject/arches pull request #9854
Opened 2023-08-01 00:34 UTC by njkim

### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

Support tileid in input data

### Issues Solved

#9749 

### Checklist

-   [ ] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: 
*   Found by: @ 
*   Tested by: @ 
*   Designed by: @ 

### Further comments

2023-08-09 18:03 UTC, chiatt requested changes
This is looking good Namjun. Just a few comments that would tighten things up a bit.

2023-08-09 22:45 UTC, njkim commented on arches/app/etl_modules/branch_excel_exporter.py
> +    def dictfetchall(self, cursor):
good point!

2023-08-10 00:41 UTC, njkim commented on arches/app/etl_modules/branch_excel_exporter.py
> +from django.http import HttpResponse
Removed

2023-08-10 00:41 UTC, njkim commented on arches/app/media/js/views/components/etl_modules/branch-excel-exporter.js
> +            this.getGraphs = async function(){
Good suggestion!

2023-08-10 00:42 UTC, njkim commented on arches/app/etl_modules/branch_excel_exporter.py
> +    def get_graphs(self, request):
done

2023-08-10 00:42 UTC, njkim commented on arches/app/etl_modules/branch_excel_exporter.py
> +from arches.app.models.models import GraphModel, Node, File, TempFile
done

2023-08-10 12:42 UTC, chiatt commented on arches/app/models/migrations/9748_branch_excel_exporter.py
> +        ('models', '9746_related_resource_post_save_bug'),
This dependency now needs to change to:  `9744_add_tile_excel_importer`

2023-08-10 12:44 UTC, chiatt approved these changes

2023-08-10 13:21 UTC, merged