[WIP] Add node configuration for requiring files to be images #9333
archesproject/arches pull request #9934
Opened 2023-08-16 18:43 UTC by jacobtylerwalls

### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change
WIP for discussion.

Currently, this PR adds `imagesOnly` configuration to `file-list` nodes so that if set, the validator will reject anything that's not an image. This relies on Django's built-in image validation.

Next step would be to add widget fields for title, caption, description

### Issues Solved
Closes #9333

### Checklist

-   [ ] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: Getty Conservation Institute
*   Found by: @chiatt
*   Tested by: @jacobtylerwalls
*   Designed by: @ 

### Further comments
Still a bug to work out with uploading an invalid file to an imagesOnly node, then selecting a correct file and saving (without clearing the edits in between). Looks like current error handling depends on dropzone returning an error, and doesn't gracefully handle the python backend retuning an error.

2023-09-21 01:06 UTC, apeters requested changes
<img width="629" alt="Screenshot 2023-09-20 at 5 59 09 PM" src="https://github.com/archesproject/arches/assets/823773/428e45d6-b804-41dd-8204-d8c039f5e823">

I'm not sure what the difference between `title` and `caption` are.  Maybe only one or the other is needed.  Also the report never utilizes any of these values.  I would assume that the `alt` attribute of the image (and the file too), would use either the `title` or `caption`.  Not sure where the description shows up.  Maybe that's a text block next to the image or file.
We will probably need further discussion on that.

2023-09-21 11:24 UTC, jacobtylerwalls commented
I’m starting to think we should call that second input “alt text” and just forget caption so that people are inspired to write good alt texts instead of good captions/bad alt texts.

If we were building something simple like a blog with captioned images, I guess a representative title for an image would be “Opening Day 2024” or “Benjamin Franklin, 17xx-18xx” with captions, respectively, “Better things to come?”, “Philadelphia’s most famous resident”, neither of which describe the image content in enough detail for an alt text. The alt texts would need to be something like “patrons queuing outside the XYZ Museum’s new location” and “a bust of Benjamin Franklin”. But Arches isn’t a blog, so maybe we can just have title, alt text, and a more verbose description field.

Some validation on the length of the alt text would be nice to prevent people from spamming screen readers with a wall of text.

2023-09-21 14:40 UTC, jacobtylerwalls commented on arches/app/templates/views/components/datatypes/file-list.htm
> +    <div class="node-config-item">
Nice catch. Turns out this is also a problem with the maximum number of files control just above it (double checked on 7.5)

2023-09-21 14:45 UTC, jacobtylerwalls commented
> We will probably need further discussion on that.

Exactly yeah, I figured putting this up for review would stir some design discussion, broke that out into #10050.

2023-09-21 15:56 UTC, jacobtylerwalls commented on arches/app/templates/views/components/datatypes/file-list.htm
> +    <div class="node-config-item">
#10059

2023-09-21 15:57 UTC, jacobtylerwalls commented on arches/app/templates/views/components/widgets/file.htm
> +                                <label for="title">Title</label>
Very helpful. [9f3d8be](https://github.com/archesproject/arches/pull/9934/commits/9f3d8be851b8a8fabea2e8448439fbbe640123e1)

2023-09-26 22:15 UTC, jacobtylerwalls commented
@chiatt @apeters 

Updated with the changes we discussed yesterday:
- redesign metadata fields, add "?" icon and dropdown
- require alt texts (server-side) for image-only nodes
- localize string metadata

In another PR I'll look at #10059. If we want to show anything on the report I figure we should get more design input on #10050.

2023-10-24 00:23 UTC, jacobtylerwalls commented
I keep finding more little nits with manipulating the widget (e.g. removing one of multiple files) while there's unsaved data. Unfortunately the complexity level is already higher than I'd like!

This is a lot closer, but there's still an issue with:
1. Upload file, save metadata
2. Edit metadata
Result: form not detected in dirty state, no save control

I'll take a look tomorrow.

2023-10-24 17:55 UTC, jacobtylerwalls commented
Thanks for your patience @apeters, this is ready for another look.

2023-10-27 22:01 UTC, apeters requested changes
resaving a file, doesn't clear out dirty state.  See this: https://recordit.co/6Wr5ILUpab

2023-10-30 21:46 UTC, apeters approved these changes
looks good @jacobtylerwalls !

2023-10-30 21:46 UTC, merged

2023-10-30 21:50 UTC, jacobtylerwalls commented
Thanks for the review!